version: "3.5"

x-volumes:
  &default-back-volumes
  - /mnt/data/taiga/static:/taiga-back/static
  - /mnt/data/taiga/media:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py


services:

  taiga-back:
    image: taigaio/taiga-back:latest
    restart: unless-stopped
    volumes: *default-back-volumes
    env_file:
      - variables.env
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    restart: unless-stopped
    volumes: *default-back-volumes
    env_file:
      - variables.env
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: unless-stopped
    volumes:
      - /mnt/data/taiga/async-rabbitmq:/var/lib/rabbitmq
    env_file:
      - variables.env
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    env_file:
      - variables.env
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    env_file:
      - variables.env
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    env_file:
      - variables.env
    volumes:
      - /mnt/data/taiga/events-rabbitmq:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    env_file:
      - variables.env
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "8700:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - /mnt/data/taiga/static:/taiga/static
      - /mnt/data/taiga/media:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:

