version: "3.5"

x-volumes:
  &default-back-volumes
  - /mnt/data/taiga/static:/taiga-back/static
  - /mnt/data/taiga/static:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py

services:
  taiga-manage:
    image: taigaio/taiga-back:latest
    environment:
      - CELERY_ENABLED="False"
    env_file:
      - variables.env
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
    volumes: *default-back-volumes
    networks:
      - taiga
